-- criação do banco de dados

-- MySQL Script generated by MySQL Workbench
-- Sat Jan 10 21:53:33 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema salaodebeleza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema salaodebeleza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `salaodebeleza` DEFAULT CHARACTER SET utf8 ;
USE `salaodebeleza` ;

-- -----------------------------------------------------
-- Table `salaodebeleza`.`Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaodebeleza`.`Serviço` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descrição` VARCHAR(45) NOT NULL,
  `valor_base` DECIMAL(10,2) NOT NULL,
  `tempo_estimado` TIME NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaodebeleza`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaodebeleza`.`Admin` (
  `ID` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
